### ISSUE TITLE
add remarkable-tablet label/tag

### ISSUE THREAD

**Issue by nlack** [canselcik/RemarkableFramebuffer#1]
Hey, really like you work :+1: 
Would be great, if you add the `remarkable-tablet` label/tag to this repo so others can find you great work better.

See https://github.com/topics/remarkable-tablet

**Comment by canselcik** [comment]
Thank you, I've added the `remarkable-tablet` tag just now.

I'm getting a build with `libfreetype` used for rendering the text right now. API getting more and more robust every day. :)
